### ISSUE TITLE
Nothing but lies

### ISSUE THREAD

**Issue by wnelson03** [homeless1337/KeyAuth-Source-leak#2]
I never generated any license keys without permission, you sent me a license key to use and I used it. Also the website didn't get "shelled". Shelling is when a malicious file is uploaded to the website. That was not the case, I gave trinityseal owner access and he backstabbed. I know you're turnt up that your stolen code barely pays the bills, though you don't need to lie about other projects.

**Comment by homeless1337** [comment]
Bro dont even try, you used cheato fn without my perms all the time.
